### ISSUE TITLE
Hide Header on Title Slide

### ISSUE THREAD

**Issue by jensbri** [shafayetShafee/reveal-header#13]
Hi.

Excellent work. Thank you.
I'd like to hide the header on the title slide (redundant information such as the author and title of the slide deck, otherwise).
Am I missing an option to do that?

Cheers,
Jens

**Comment by shafayetShafee** [comment]
No, there's no direct option for that, Maybe I can create one to hide header text from the title slide 😃.

However, FYI, if you use the `title-as-header` or `subtitle-as-header` options title or subtitle will be used as header text and they will not be shown in the header of the title slide.

**Comment by shafayetShafee** [comment]
Okay, I have added an option `hide-from-titleSlide`. Use `hide-from-titleSlide: "text"` to remove header text from the title slide. See the example section in the readme.

**Comment by shafayetShafee** [comment]
@jensbri, I am closing this issue now. Feel free to reopen if necessary.
